# fly.toml app configuration file generated for bookbook on 2025-09-03T11:08:35+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bookbook'
primary_region = 'nrt'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[http_service.ports]]
port = 80
handlers = ["http"]
force_https = true

[[http_service.ports]]
port = 443
handlers = ["tls", "http"]

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1